/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WordPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var WordPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("PLUGIN LOADED");
    this.addCommand({
      id: "add-word",
      name: "Add word",
      callback: async () => {
        new import_obsidian.Notice("COMMAND WORKS");
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("No file open");
          return;
        }
        const content = await this.app.vault.read(file);
        await this.app.vault.modify(
          file,
          content + "\n- new word"
        );
        new import_obsidian.Notice("Word added");
      }
    });
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsic3JjL21haW4udHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImltcG9ydCB7IE5vdGljZSwgUGx1Z2luIH0gZnJvbSAnb2JzaWRpYW4nO1xuXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBXb3JkUGx1Z2luIGV4dGVuZHMgUGx1Z2luIHtcblxuXHRhc3luYyBvbmxvYWQoKSB7XG5cblx0XHRjb25zb2xlLmxvZyhcIlBMVUdJTiBMT0FERURcIik7XG5cblx0XHR0aGlzLmFkZENvbW1hbmQoe1xuXHRcdFx0aWQ6ICdhZGQtd29yZCcsXG5cdFx0XHRuYW1lOiAnQWRkIHdvcmQnLFxuXHRcdFx0Y2FsbGJhY2s6IGFzeW5jICgpID0+IHtcblxuXHRcdFx0XHRuZXcgTm90aWNlKCdDT01NQU5EIFdPUktTJyk7XG5cblx0XHRcdFx0Y29uc3QgZmlsZSA9IHRoaXMuYXBwLndvcmtzcGFjZS5nZXRBY3RpdmVGaWxlKCk7XG5cblx0XHRcdFx0aWYgKCFmaWxlKSB7XG5cdFx0XHRcdFx0bmV3IE5vdGljZSgnTm8gZmlsZSBvcGVuJyk7XG5cdFx0XHRcdFx0cmV0dXJuO1xuXHRcdFx0XHR9XG5cblx0XHRcdFx0Y29uc3QgY29udGVudCA9IGF3YWl0IHRoaXMuYXBwLnZhdWx0LnJlYWQoZmlsZSk7XG5cblx0XHRcdFx0YXdhaXQgdGhpcy5hcHAudmF1bHQubW9kaWZ5KFxuXHRcdFx0XHRcdGZpbGUsXG5cdFx0XHRcdFx0Y29udGVudCArICdcXG4tIG5ldyB3b3JkJ1xuXHRcdFx0XHQpO1xuXG5cdFx0XHRcdG5ldyBOb3RpY2UoJ1dvcmQgYWRkZWQnKTtcblx0XHRcdH1cblx0XHR9KTtcblx0fVxufSJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQSxzQkFBK0I7QUFFL0IsSUFBcUIsYUFBckIsY0FBd0MsdUJBQU87QUFBQSxFQUU5QyxNQUFNLFNBQVM7QUFFZCxZQUFRLElBQUksZUFBZTtBQUUzQixTQUFLLFdBQVc7QUFBQSxNQUNmLElBQUk7QUFBQSxNQUNKLE1BQU07QUFBQSxNQUNOLFVBQVUsWUFBWTtBQUVyQixZQUFJLHVCQUFPLGVBQWU7QUFFMUIsY0FBTSxPQUFPLEtBQUssSUFBSSxVQUFVLGNBQWM7QUFFOUMsWUFBSSxDQUFDLE1BQU07QUFDVixjQUFJLHVCQUFPLGNBQWM7QUFDekI7QUFBQSxRQUNEO0FBRUEsY0FBTSxVQUFVLE1BQU0sS0FBSyxJQUFJLE1BQU0sS0FBSyxJQUFJO0FBRTlDLGNBQU0sS0FBSyxJQUFJLE1BQU07QUFBQSxVQUNwQjtBQUFBLFVBQ0EsVUFBVTtBQUFBLFFBQ1g7QUFFQSxZQUFJLHVCQUFPLFlBQVk7QUFBQSxNQUN4QjtBQUFBLElBQ0QsQ0FBQztBQUFBLEVBQ0Y7QUFDRDsiLAogICJuYW1lcyI6IFtdCn0K
